# Generated by Django 3.0.1 on 2019-12-30 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suv1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='writer',
            field=models.CharField(default='charField', max_length=8),
        ),
    ]
